### PR TITLE
Update SpongePowered to 8.5

### PR DESCRIPTION
**Pull request by OptimusZeGaming**
A commit to update spongepowered to 8.5

### CODE REVIEW

**Comment by SuperMartijn642** [comment]
What is the reason for this PR, why would mixin need to be updated?

Mixin 0.8.2 is the latest version of mixin which doesn't break other mods using a mixin version older than 0.8.2. Hence I specifically chose to include that version.

**Comment by OptimusZeGaming** [comment]
> What is the reason for this PR, why would mixin need to be updated?
> 
> Mixin 0.8.2 is the latest version of mixin which doesn't break other mods using a mixin version older than 0.8.2. Hence I specifically chose to include that version.

The Moving Elevator mods are not compatible with the DynamX mods, as they use version 8.5, which is not compatible with version 8.2.

**Comment by SuperMartijn642** [comment]
> The Moving Elevator mods are not compatible with the DynamX mods

The only mod I can find with 'DynamX' in its name, is [DynamX Physics Mod](https://www.curseforge.com/minecraft/mc-mods/dynamx). I haven't had any reports from people for incompatibilities with that and seeing as the download count is not that high, I think I would rather keep support with the mods using mixin 0.8.2 or older.

> ... as they use version 8.5, which is not compatible with version 8.2.

Many 1.12 mods use mixin versions older than 0.8.2. This means DynamX Physics Mod will be incompatible with all of those.

I specifically copied what [Mixin 0.7-0.8 Compatibility](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility) does, which is make sure mixin 0.8.2 gets loaded before any other mod loads their version of mixin. This is the only solution I found to incompatibilities with many popular 1.12 mods such as VanillaFix.
Since making that change I haven't had any reports of mixin incompatibilities.

Mixin 0.8.5 is simply too new for 1.12 mods as even mixin 0.8.2 already came out 3 years after Minecraft 1.13 was released.

**Comment by OptimusZeGaming** [comment]
I see.

**Comment by OptimusZeGaming** [comment]
Can I create a release on my fork with mixin version 8.5?

**Comment by SuperMartijn642** [comment]
You mean like as a release on GitHub? I don't mind that.

Just don't upload it to like CurseForge or Modrinth and that be fine 😅

**Pull request closed without merging**
